[tool.black]
line-length = 88
target-version = ['py311']

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
tag_format = "v{version}"
bump_message = "chore(release): {current_version} → {new_version}"
changelog_file = "CHANGELOG.md"



